import { useMemo } from "react";

const FORCED_HIDDEN_COLUMN_KEYS = new Set([
  "position",
  "department",
  "constructionSite",
  "documentExpiry",
  "status",
]);

const buildAvailableColumns = ({
  showDepartmentColumn,
  showCounterpartyColumn,
}) =>
  [
    { key: "index", label: "№" },
    { key: "fullName", label: "ФИО" },
    { key: "position", label: "Должность" },
    ...(showDepartmentColumn
      ? [{ key: "department", label: "Подразделение" }]
      : []),
    ...(showCounterpartyColumn
      ? [{ key: "counterparty", label: "Контрагент" }]
      : []),
    { key: "constructionSite", label: "Объект" },
    { key: "citizenship", label: "Гражданство" },
    { key: "isUpload", label: "ЗУП" },
    { key: "zupUploadedAt", label: "Дата" },
    { key: "files", label: "Файлы" },
    { key: "documentExpiry", label: "Срок действия док." },
    { key: "status", label: "Статус" },
  ].filter((column) => !FORCED_HIDDEN_COLUMN_KEYS.has(column.key));

const useEmployeesPageViewModels = ({
  backgroundLoading,
  employees,
  totalCount,
  canExport,
  searchText,
  statusFilter,
  activeFilters,
  setSearchText,
  setStatusFilter,
  handleResetFilters,
  onRemoveActiveFilter,
  showDepartmentColumn,
  showCounterpartyColumn,
  hiddenColumns,
  handleToggleColumn,
  handleResetColumns,
  handleAdd,
  handleRequest,
  setIsImportModalOpen,
  setIsSecurityModalOpen,
  filteredEmployees,
  loading,
  currentPage,
  pageSize,
  departments,
  uniqueFilters,
  filterOptions,
  defaultCounterpartyId,
  user,
  resetTrigger,
  canDeleteEmployee,
  canMarkForDeletion,
  handleView,
  handleEdit,
  handleDelete,
  handleViewFiles,
  handleMarkForDeletion,
  handleDepartmentChange,
  handleUploadStatusChange,
  handlePaginationChange,
  setTableFilters,
  handleConstructionSitesEdit,
  isModalOpen,
  editingEmployee,
  isViewModalOpen,
  viewingEmployee,
  isFilesModalOpen,
  filesEmployee,
  isSitesModalOpen,
  sitesEmployee,
  isRequestModalOpen,
  tableFilters,
  isExportModalOpen,
  isImportModalOpen,
  isSecurityModalOpen,
  setIsModalOpen,
  setEditingEmployee,
  handleFormSuccess,
  handleCheckInn,
  setIsViewModalOpen,
  setViewingEmployee,
  handleMobileViewEdit,
  closeFilesModal,
  handleFilesUpdated,
  closeSitesModal,
  handleSitesUpdated,
  setIsRequestModalOpen,
  refetchEmployees,
  setIsExportModalOpen,
  sortBy,
  sortOrder,
  handleSortChange,
  statsPeriod,
  setStatsPeriod,
  portalStats,
  portalStatsLoading,
  exportQueryParams,
}) => {
  const availableColumns = useMemo(
    () =>
      buildAvailableColumns({
        showDepartmentColumn,
        showCounterpartyColumn,
      }),
    [showCounterpartyColumn, showDepartmentColumn],
  );

  const toolbarView = useMemo(
    () => ({
      backgroundLoading,
      loadedEmployeesCount: employees.length,
      totalCount,
      canExport,
    }),
    [backgroundLoading, employees.length, totalCount, canExport],
  );

  const toolbarFilters = useMemo(
    () => ({
      searchText,
      statusFilter,
      activeFilters,
      onSearchTextChange: setSearchText,
      onStatusFilterChange: setStatusFilter,
      onResetFilters: handleResetFilters,
      onRemoveActiveFilter,
    }),
    [
      searchText,
      statusFilter,
      activeFilters,
      setSearchText,
      setStatusFilter,
      handleResetFilters,
      onRemoveActiveFilter,
    ],
  );

  const toolbarColumns = useMemo(
    () => ({
      availableColumns,
      hiddenColumns,
      onToggleColumn: handleToggleColumn,
      onResetColumns: handleResetColumns,
    }),
    [availableColumns, hiddenColumns, handleToggleColumn, handleResetColumns],
  );

  const toolbarActions = useMemo(
    () => ({
      onAdd: handleAdd,
      onRequest: handleRequest,
      onImport: () => setIsImportModalOpen(true),
      onExport: () => setIsExportModalOpen(true),
      onSecurity: () => setIsSecurityModalOpen(true),
    }),
    [
      handleAdd,
      handleRequest,
      setIsImportModalOpen,
      setIsExportModalOpen,
      setIsSecurityModalOpen,
    ],
  );

  const employeesListModel = useMemo(
    () => ({
      filteredEmployees,
      totalCount,
      loading,
      currentPage,
      pageSize,
      departments,
      canExport,
      showDepartmentColumn,
      showCounterpartyColumn,
      uniqueFilters,
      filterOptions,
      tableFilters,
      defaultCounterpartyId,
      userCounterpartyId: user?.counterpartyId,
      resetTrigger,
      hiddenColumns,
      canDeleteEmployee,
      canMarkForDeletion,
      sortBy,
      sortOrder,
      statsPeriod,
      portalStats,
      portalStatsLoading,
    }),
    [
      filteredEmployees,
      totalCount,
      loading,
      currentPage,
      pageSize,
      departments,
      canExport,
      showDepartmentColumn,
      showCounterpartyColumn,
      uniqueFilters,
      filterOptions,
      tableFilters,
      defaultCounterpartyId,
      user?.counterpartyId,
      resetTrigger,
      hiddenColumns,
      canDeleteEmployee,
      canMarkForDeletion,
      sortBy,
      sortOrder,
      statsPeriod,
      portalStats,
      portalStatsLoading,
    ],
  );

  const employeesListActions = useMemo(
    () => ({
      onView: handleView,
      onEdit: handleEdit,
      onDelete: handleDelete,
      onViewFiles: handleViewFiles,
      onMarkForDeletion: handleMarkForDeletion,
      onDepartmentChange: handleDepartmentChange,
      onUploadStatusChange: handleUploadStatusChange,
      onPaginationChange: handlePaginationChange,
      onFiltersChange: setTableFilters,
      onConstructionSitesEdit: handleConstructionSitesEdit,
      onSortChange: handleSortChange,
      onStatsPeriodChange: setStatsPeriod,
    }),
    [
      handleView,
      handleEdit,
      handleDelete,
      handleViewFiles,
      handleMarkForDeletion,
      handleDepartmentChange,
      handleUploadStatusChange,
      handlePaginationChange,
      setTableFilters,
      handleConstructionSitesEdit,
      handleSortChange,
      setStatsPeriod,
    ],
  );

  const employeesModalModel = useMemo(
    () => ({
      isModalOpen,
      editingEmployee,
      isViewModalOpen,
      viewingEmployee,
      isFilesModalOpen,
      filesEmployee,
      isSitesModalOpen,
      sitesEmployee,
      isRequestModalOpen,
      filteredEmployees,
      tableFilters,
      userRole: user?.role,
      userCounterpartyId: user?.counterpartyId,
      defaultCounterpartyId,
      userId: user?.id,
      isExportModalOpen,
      isImportModalOpen,
      isSecurityModalOpen,
      exportQueryParams,
    }),
    [
      isModalOpen,
      editingEmployee,
      isViewModalOpen,
      viewingEmployee,
      isFilesModalOpen,
      filesEmployee,
      isSitesModalOpen,
      sitesEmployee,
      isRequestModalOpen,
      filteredEmployees,
      tableFilters,
      user?.role,
      user?.counterpartyId,
      defaultCounterpartyId,
      user?.id,
      isExportModalOpen,
      isImportModalOpen,
      isSecurityModalOpen,
      exportQueryParams,
    ],
  );

  const employeesModalActions = useMemo(
    () => ({
      setIsModalOpen,
      setEditingEmployee,
      onFormSuccess: handleFormSuccess,
      onCheckInn: handleCheckInn,
      setIsViewModalOpen,
      setViewingEmployee,
      onEditEmployee: handleEdit,
      onMobileViewEdit: handleMobileViewEdit,
      onCloseFilesModal: closeFilesModal,
      onFilesUpdated: handleFilesUpdated,
      onCloseSitesModal: closeSitesModal,
      onSitesUpdated: handleSitesUpdated,
      setIsRequestModalOpen,
      refetchEmployees,
      setIsExportModalOpen,
      setIsImportModalOpen,
      setIsSecurityModalOpen,
    }),
    [
      setIsModalOpen,
      setEditingEmployee,
      handleFormSuccess,
      handleCheckInn,
      setIsViewModalOpen,
      setViewingEmployee,
      handleEdit,
      handleMobileViewEdit,
      closeFilesModal,
      handleFilesUpdated,
      closeSitesModal,
      handleSitesUpdated,
      setIsRequestModalOpen,
      refetchEmployees,
      setIsExportModalOpen,
      setIsImportModalOpen,
      setIsSecurityModalOpen,
    ],
  );

  return {
    toolbarView,
    toolbarFilters,
    toolbarColumns,
    toolbarActions,
    employeesListModel,
    employeesListActions,
    employeesModalModel,
    employeesModalActions,
  };
};

export default useEmployeesPageViewModels;
