import { useMemo } from "react";
import { buildMobileDocumentSections } from "./MobileEmployeeDocumentSections";
import { buildMobilePrimarySections } from "./MobileEmployeePrimarySections";

export const useMobileEmployeeFormSections = ({
  employee,
  user,
  defaultCounterpartyId,
  fireLoading,
  activateLoading,
  handleFire,
  handleReinstate,
  handleDeactivate,
  handleActivate,
  getFieldProps,
  formatInn,
  handleInnBlur,
  noAutoFillProps,
  latinInputError,
  antiAutofillIds,
  handleFullNameChange,
  loadingReferences,
  positions,
  citizenships,
  handleCitizenshipChange,
  formatPhoneNumber,
  requiresPatent,
  formatSnils,
  formatBankAccountNumber,
  formatKig,
  passportType,
  setPassportType,
  formatRussianPassportNumber,
  documentProfileCode,
  documentProfilesConfig,
  ensureEmployeeId,
  formatPatentNumber,
  formatBlankNumber,
  loadingCounterparties,
  availableCounterparties,
}) => {
  return useMemo(() => {
    const items = [
      ...buildMobilePrimarySections({
        employee,
        user,
        defaultCounterpartyId,
        fireLoading,
        activateLoading,
        onFire: handleFire,
        onReinstate: handleReinstate,
        onDeactivate: handleDeactivate,
        onActivate: handleActivate,
        getFieldProps,
        formatInn,
        handleInnBlur,
        noAutoFillProps,
        latinInputError,
        antiAutofillIds,
        handleFullNameChange,
        loadingReferences,
        positions,
        citizenships,
        handleCitizenshipChange,
        formatPhoneNumber,
      }),
    ];

    items.push(
      ...buildMobileDocumentSections({
        getFieldProps,
        requiresPatent,
        formatSnils,
        formatBankAccountNumber,
        formatKig,
        passportType,
        setPassportType,
        formatRussianPassportNumber,
        documentProfileCode,
        documentProfilesConfig,
        noAutoFillProps,
        employee,
        ensureEmployeeId,
        formatPatentNumber,
        formatBlankNumber,
        loadingCounterparties,
        availableCounterparties,
      }),
    );

    return items;
  }, [
    activateLoading,
    antiAutofillIds,
    availableCounterparties,
    citizenships,
    defaultCounterpartyId,
    documentProfileCode,
    documentProfilesConfig,
    employee,
    ensureEmployeeId,
    fireLoading,
    formatBlankNumber,
    formatBankAccountNumber,
    formatInn,
    formatKig,
    formatPatentNumber,
    formatPhoneNumber,
    formatRussianPassportNumber,
    formatSnils,
    getFieldProps,
    handleActivate,
    handleCitizenshipChange,
    handleDeactivate,
    handleFire,
    handleFullNameChange,
    handleInnBlur,
    handleReinstate,
    latinInputError,
    loadingCounterparties,
    loadingReferences,
    noAutoFillProps,
    passportType,
    positions,
    requiresPatent,
    setPassportType,
    user,
  ]);
};
